// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0VfMrEqmuwNRuq3iONOfpLKkH5qaDfCE',
    appId: '1:241544068744:web:12161e8c37959ab88fe93d',
    messagingSenderId: '241544068744',
    projectId: 'test-91f1f',
    authDomain: 'test-91f1f.firebaseapp.com',
    databaseURL: 'https://test-91f1f-default-rtdb.firebaseio.com',
    storageBucket: 'test-91f1f.appspot.com',
    measurementId: 'G-P6C0J1D6PK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmlYSmCMhLOudq6-zSMGs0j_mbsqK-47E',
    appId: '1:241544068744:android:9abea8e50c331d9b8fe93d',
    messagingSenderId: '241544068744',
    projectId: 'test-91f1f',
    databaseURL: 'https://test-91f1f-default-rtdb.firebaseio.com',
    storageBucket: 'test-91f1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_poWM77-3wdFj2aOooytca5r4ECFsURs',
    appId: '1:241544068744:ios:4fd195595a62b0e38fe93d',
    messagingSenderId: '241544068744',
    projectId: 'test-91f1f',
    databaseURL: 'https://test-91f1f-default-rtdb.firebaseio.com',
    storageBucket: 'test-91f1f.appspot.com',
    androidClientId: '241544068744-0voas2qhs4115td0ncpj2g7mqqvtta2t.apps.googleusercontent.com',
    iosClientId: '241544068744-cmpl317j67luh0ilerr4qpft0g4q14ql.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymmanagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_poWM77-3wdFj2aOooytca5r4ECFsURs',
    appId: '1:241544068744:ios:4fd195595a62b0e38fe93d',
    messagingSenderId: '241544068744',
    projectId: 'test-91f1f',
    databaseURL: 'https://test-91f1f-default-rtdb.firebaseio.com',
    storageBucket: 'test-91f1f.appspot.com',
    androidClientId: '241544068744-0voas2qhs4115td0ncpj2g7mqqvtta2t.apps.googleusercontent.com',
    iosClientId: '241544068744-cmpl317j67luh0ilerr4qpft0g4q14ql.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymmanagement',
  );
}
